Обработка кликов карточки фильма и попапа
htmlacademy-ecmascript/912453-cinemaddict-17 pull request #9
Opened 2022-05-28 16:24 UTC by MrDimk

2022-05-29 12:45 UTC, KletskovG requested changes

2022-05-29 12:45 UTC, KletskovG commented on src/presenter/film-presenter.js
> +    this.#filmCardView.setWatchlistChangeHandler(this.#onWatchlistChange);
Тут код 2 раза дублируется

Так точно должно быть?

2022-05-29 12:45 UTC, KletskovG commented on src/view/films-view/film-card-view.js
> +  watchlistButtonOn() {
Тут очень сильно в глаз бросается дублирование кода

Можно написать функцию, которая будет примерно так выглядеть

```js
function toggleClass(element, class) {
  element.classList.toggle(class);
}

toggleClass(this.buttons.watchList, 'film-card__controls-item--active');
```

Если функция toggle не подходит, то можно добавить еще один аргумент, который будет принимать булевое значение и на его основе делать add или remove

2022-05-29 12:45 UTC, KletskovG commented on src/view/films-view/film-details-view.js
> +  watchlistButtonOn() {
Тут такая же история с дублированием кода

2022-05-30 21:46 UTC, MrDimk commented on src/view/films-view/film-card-view.js
> +  watchlistButtonOn() {
Лучше с дополнительным аргументом - еще до текущего варианта я сделал как раз на функции .classList.toggle(), но на тестах заметил сценарий, при котором режим отображения внутри попапа может начать несовпадать с карточкой фильма, и более простым решением показалось построить логику на add/remove

2022-06-03 10:18 UTC, merged